# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

version: 2
updates:
  # Maintain dependencies for GitHub Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for TCR Go Modules

  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tcr-doc"
    schedule:
      interval: "daily"

  # Maintain dependencies for TCR Web Application

  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "daily"

  # Maintain dependencies for C# examples

  - package-ecosystem: "nuget"
    directory: "/examples/csharp-dotnet"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Elixir examples

  - package-ecosystem: "mix"
    directory: "/examples/elixir-mix"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go examples

  - package-ecosystem: "gomod"
    directory: "/examples/go-bazel"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/examples/go-go-tools"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/examples/go-gotestsum"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/examples/go-make"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Java examples

  - package-ecosystem: "maven"
    directory: "/examples/java-maven"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/examples/java-maven-wrapper"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/examples/java-gradle"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/examples/java-gradle-wrapper"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Javascript examples

  - package-ecosystem: "npm"
    directory: "/examples/javascript-yarn"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Kotlin examples

  - package-ecosystem: "maven"
    directory: "/examples/kotlin-maven"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/examples/kotlin-maven-wrapper"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/examples/kotlin-gradle"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/examples/kotlin-gradle-wrapper"
    schedule:
      interval: "weekly"

  # Maintain dependencies for PHP examples

  - package-ecosystem: "composer"
    directory: "/examples/php-phpunit"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python examples

  - package-ecosystem: "pip"
    directory: "/examples/python-bazel"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/examples/python-pytest"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Rust examples

  - package-ecosystem: "cargo"
    directory: "/examples/rust-cargo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/examples/rust-nextest"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Typescript examples

  - package-ecosystem: "npm"
    directory: "/examples/typescript-yarn"
    schedule:
      interval: "weekly"
